### ISSUE TITLE
Losing focus when enter something in custom input with validation enabled.

### ISSUE THREAD

**Issue by sehgalrishabh** [formium/formik#3302]
https://codesandbox.io/s/formik-example-forked-w0bub?file=/index.js

**Comment by hereisfahad** [comment]
@sehgalrishabh You can fix it by extracting the custom input into a separate component like in the [formik docs](https://formik.org/docs/api/field#example)
[fixed version](https://codesandbox.io/s/formik-example-forked-0hmfw?file=/index.js)

**Comment by hawekotte** [comment]
Wanted to say that this bug is still present in `Formik` `2.2.9` with `React` and `React Dom` `17.0.2` _if_ you are using an inline function to define the component. (Is this due to the fact that a re-render occurs and the inline function is recreated?) I put together [an example](https://codesandbox.io/s/formik-broken-as-jjn6l) showing this off.

**Comment by johnrom** [comment]
> if you are using an inline function to define the component

This is not a component, it's a function. A functional component's definition should be constant across the lifetime of the app. This is related to React not specific to Formik. It's not outlined explicitly in the React documentation, but it is hinted at here:

https://reactjs.org/docs/higher-order-components.html#dont-use-hocs-inside-the-render-method

In essence, it reads: "don't create new components during render."
